name: 'Pipeline test lambda python'
description: 'test lambda python aws'
inputs:
  PATH_TO_REQUIREMENTS: 
    description: 'Path to requirements.txt'
    required: true

runs:
  using: "composite"
  steps:
    - name: Path to requirements.txt
      run: echo ${{ inputs.PATH_TEST_FOLDER }}.
      shell: bash
    
    - name: Checkout
      uses: actions/checkout@v4  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'
        cache: 'pip'
    
    - name: Install dependencies    
      run: |
        python -m pip install --upgrade pip
        cd ${{ inputs.PATH_TEST_FOLDER }}
        pip install -r requirements.txt    
      shell: bash

    - name: Run tests    
      run: |
        python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        python -m pytest --cov
      shell: bash

    - name: Upload report      
      uses: actions/upload-artifact@v3
      with:
        name: test-results.xml
        path: junit/test-results.xml  